services:
  postgres:
    image: postgres:15
    container_name: pss-postgres
    environment:
      POSTGRES_DB: pss_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    container_name: pss-minio
    ports:
      - "9000:9000" # Porta da API S3
      - "9001:9001" # Porta do Console UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"